### ISSUE TITLE
childOf

### ISSUE THREAD

**Issue by afoninsky** [RisingStack/opentracing-auto#10]
Is it possible to add this instrumentalization root span as a child of another span?

Usecase: I already have existing trace come from another service, and want to append to it.

**Comment by hekike** [comment]
Hmm, good question, at the moment it automatically pickups root spans by specific HTTP headers.
Like: https://github.com/RisingStack/opentracing-auto/blob/master/src/instrumentation/express.js#L26

**Comment by afoninsky** [comment]
Does async hooks look suitable for passing context downstairs? It could be universal instrumetralization solution IMHO.
https://nodejs.org/api/async_hooks.html

**Comment by hekike** [comment]
This library already uses `async_hooks` :)
