### ISSUE TITLE
url.format will ignore `path` parameter, use `pathname` and `search` instead

### ISSUE THREAD

**Issue by xinchaobeta** [RisingStack/opentracing-auto#5]
https://github.com/RisingStack/opentracing-auto/blob/4c0017337829865cd06014889b9617261f51d2b8/src/instrumentation/httpClient.js#L28

**Comment by hekike** [comment]
Thanks landed as `1.5.1` by https://github.com/RisingStack/opentracing-auto/commit/bc4751ed965fea165f301e129b8c094854274794

**Comment by hekike** [comment]
Sorry I mean by: https://github.com/RisingStack/opentracing-auto/commit/1b79ac35b44e82b7ce29f53e110db1b138e79d2a
