### ISSUE TITLE
use `req.get('host')` to replace `req.hostname` , so that the port information can be preserved 

### ISSUE THREAD

**Issue by xinchaobeta** [RisingStack/opentracing-auto#6]
https://github.com/RisingStack/opentracing-auto/blob/4c0017337829865cd06014889b9617261f51d2b8/src/instrumentation/express.js#L25

**Comment by hekike** [comment]
Thanks landed as `1.5.1` by https://github.com/RisingStack/opentracing-auto/commit/1b79ac35b44e82b7ce29f53e110db1b138e79d2a
